/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/venues` | `/venues`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events/scraper` | `/events/scraper`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events/upload` | `/events/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events/list/past` | `/events/list/past`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events/list/upcoming` | `/events/list/upcoming`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/venues` | `/venues`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/events/scraper` | `/events/scraper`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/events/upload` | `/events/upload`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/events/list/past` | `/events/list/past`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/events/list/upcoming` | `/events/list/upcoming`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/venues${`?${string}` | `#${string}` | ''}` | `/venues${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/events/scraper${`?${string}` | `#${string}` | ''}` | `/events/scraper${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/events/upload${`?${string}` | `#${string}` | ''}` | `/events/upload${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/events/list/past${`?${string}` | `#${string}` | ''}` | `/events/list/past${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/events/list/upcoming${`?${string}` | `#${string}` | ''}` | `/events/list/upcoming${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/venues` | `/venues`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events/scraper` | `/events/scraper`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events/upload` | `/events/upload`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events/list/past` | `/events/list/past`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events/list/upcoming` | `/events/list/upcoming`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
